name: running-ci
on: 
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
permissions:
  contents: read
  pull-requests: read
jobs:
  running-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
       uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: packages install
        run: pnpm install
      - name: run lint
        run: pnpm run lint
